class NegativeAmountError(Exception): ...
class ClientNotFoundError(Exception): ...
class AccountNotFoundError(Exception): ...
class WrongAmountFormat(Exception): ...
class AccountCreationError(Exception): ...
class ClientDoesNotExistError(Exception): ...
class MissingArgumentError(Exception): ...
class ExcessArgumentsError(Exception): ...